version: '3.9'
services:
  postgres:
    image: postgres:15.4
    container_name: travel-ai-postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5435:5432"
    volumes:
      - ./travel-data:/var/lib/postgresql/data

volumes:
  postgres_data:
